### ISSUE TITLE
Wrong values for NOZZLE_TO_PROBE_OFFSET

### ISSUE THREAD

**Issue by Mariuolo83** [Eryone/mega2560#7]
The values for NOZZLE_TO_PROBE_OFFSET at line 933 in THINKER V2/config/Eryone/THINKER SE/Stock with Bltouch/Configuration.h results erroneus using your "Bltouch_plate for Thinker SE" found at https://www.thingiverse.com/thing:4585251
Please update that values according to the real measures.

**Comment by Eryone** [comment]
Thanks, will update the correct value.
