### ISSUE TITLE
Tmc connection error

### ISSUE THREAD

**Issue by Chron420** [Eryone/mega2560#8]
I have updated my thinker se to tmc2209 steppers, I followed the eryone instructions, edited pin file, compiles fine but I am getting a tmc connection error on the printer lcd.  Printer works fine

If I change the configuration file to tmc2209_standalone I lose sensorless homing and a few other things
Hoping someone has a fix

Thanks in advance

**Comment by Eryone** [comment]
Hi, because the TMC2209 UART with the THINKER SE motherboard based on the hardware serial  4.
It means it can receive the signal but it can't send.

If you don't want to watch it again you can go to firmware then disable the warning info of it.
